# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt update
          sudo apt install wget ffmpeg -y
          wget -o 1.m4a http://yt.checker.in/utubebot/_%E5%94%B1%E6%AD%8C%E5%82%BE%E8%A8%88_11%E6%9C%88%E3%81%AE%E7%9B%B4%E6%92%AD.m4a
          ls -al
          ffmpeg -re -loop 1 -i 1.png -i 1.m4a -r 1 -preset ultrafast -c:a copy -f flv rtmp://a.rtmp.youtube.com/live2/d01v-aj6k-p238-ff2x-2ymk
